trigger:
  branches:
    include:
      - master
      - rel/*
  paths:
    include:
      - Ix.NET/Source/*
      - .editorconfig
      - .vsts.ix-ci.yml
      - NuGet.Config

queue: Hosted VS2017
variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
steps:
- template: .vsts.ix-shared.yml
  parameters:
    signStep:
    - task: PowerShell@2
      displayName: Authenticode Sign Packages
      inputs:
        filePath: Ix.NET/Source/build/Sign-Package.ps1
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)\artifacts