/*
 * This file is manually generated upon every change to the corresponding .resx file, using the built-in code generator.
 * However, we can't use auto-generated code because the output is different for .NET 4.5 for Metro and PLIB, due to
 * changes in the reflection APIs (search for CRIPPLED_REFLECTION in this file), and because regeneration doesn't happen
 * as part of build, but rather at design time in Visual Studio. While we likely could tweak MSBuild to force regeneration
 * using the right version of ResGen.exe, this approach turned out to be the easiest for the time being.
 * 
 * Upon adding entries to the ResX file, regenerate this file, put this comment back, and make sure to add the #if checks
 * for conditional use of the right flavor of reflection (using the CRIPPLED_REFLECTION defined symbol).
 */

// Required for the use of the GetTypeInfo extension method.
#if CRIPPLED_REFLECTION
using System.Reflection;
#endif

// GENERATED CODE starts here

namespace System.Reactive
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Core
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Core()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
#if CRIPPLED_REFLECTION
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reactive.Strings_Core", typeof(Strings_Core).GetTypeInfo().Assembly);
#else
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reactive.Strings_Core", typeof(Strings_Core).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using the Scheduler.{0} property is no longer supported due to refactoring of the API surface and elimination of platform-specific dependencies. Please include System.Reactive.PlatformServices for your target platform and use the {0}Scheduler type instead..
        /// </summary>
        internal static string CANT_OBTAIN_SCHEDULER
        {
            get
            {
                return ResourceManager.GetString("CANT_OBTAIN_SCHEDULER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OnCompleted notification doesn&apos;t have a value..
        /// </summary>
        internal static string COMPLETED_NO_VALUE
        {
            get
            {
                return ResourceManager.GetString("COMPLETED_NO_VALUE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disposable has already been assigned..
        /// </summary>
        internal static string DISPOSABLE_ALREADY_ASSIGNED
        {
            get
            {
                return ResourceManager.GetString("DISPOSABLE_ALREADY_ASSIGNED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start monitoring system clock changes..
        /// </summary>
        internal static string FAILED_CLOCK_MONITORING
        {
            get
            {
                return ResourceManager.GetString("FAILED_CLOCK_MONITORING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heap is empty..
        /// </summary>
        internal static string HEAP_EMPTY
        {
            get
            {
                return ResourceManager.GetString("HEAP_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reentrancy has been detected..
        /// </summary>
        internal static string REENTRANCY_DETECTED
        {
            get
            {
                return ResourceManager.GetString("REENTRANCY_DETECTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Observer has already terminated..
        /// </summary>
        internal static string OBSERVER_TERMINATED
        {
            get
            {
                return ResourceManager.GetString("OBSERVER_TERMINATED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This scheduler operation has already been awaited..
        /// </summary>
        internal static string SCHEDULER_OPERATION_ALREADY_AWAITED
        {
            get
            {
                return ResourceManager.GetString("SCHEDULER_OPERATION_ALREADY_AWAITED", resourceCulture);
            }
        }
    }
}
