// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT License.
// See the LICENSE file in the project root for more information.

[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ObservableExtensions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.AnonymousObservable<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.AnonymousObserver<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPatternSourceBase<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPattern<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ExperimentalAttribute))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.IEventPatternSource<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.IEventPattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.IEventSource<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.IObserver<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ITaskObservableAwaiter<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ITaskObservable<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ListObservable<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Notification))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.NotificationKind))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Notification<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ObservableBase<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Observer))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.ObserverBase<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.TimeInterval<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Timestamped))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Timestamped<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Unit))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.AsyncLock))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.CurrentThreadScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.DefaultScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.IConcurrencyAbstractionLayer))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ImmediateScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.IScheduledItem<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.IScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ISchedulerLongRunning))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ISchedulerPeriodic))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.IStopwatch))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.IStopwatchProvider))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.LocalScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.EventLoopScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.HistoricalScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.HistoricalSchedulerBase))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.NewThreadScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ScheduledItem<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ScheduledItem<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.Scheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.SchedulerOperation))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.SchedulerOperationAwaiter))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.SchedulerQueue<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.Synchronization))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.SynchronizationContextScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.TaskObservationOptions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.TaskPoolScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.ThreadPoolScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeSchedulerBase<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeSchedulerExtensions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeScheduler<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.BooleanDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.CancellationDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.CompositeDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.ContextDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.Disposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.ICancelable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.MultipleAssignmentDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.RefCountDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.ScheduledDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.SerialDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.SingleAssignmentDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.SingleAssignmentDisposableValue))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Disposables.StableCompositeDisposable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Plan<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePattern<,,,,,,,,,,,,,,,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.QueryablePlan<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.IGroupedObservable<,>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.IQbservable))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.IQbservableProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.IQbservable<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.LocalQueryMethodImplementationTypeAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.Observable))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.ObservableEx))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.Qbservable))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.QbservableEx))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.QueryDebugger))]
#if HAS_REMOTING
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.RemotingObservable))]
#endif
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.CurrentPlatformEnlightenmentProvider))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.DefaultSystemClock))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.EnlightenmentProvider))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.HostLifecycleService))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.HostResumingEventArgs))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.HostSuspendingEventArgs))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.IExceptionServices))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.IHostLifecycleNotifications))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.INotifySystemClockChanged))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.IPlatformEnlightenmentProvider))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.ISystemClock))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.PeriodicTimerSystemClockMonitor))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.PlatformEnlightenmentProvider))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.SystemClock))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.PlatformServices.SystemClockChangedEventArgs))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.AsyncSubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.BehaviorSubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.IConnectableObservable<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.ISubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.ISubject<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.ReplaySubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.Subject))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.SubjectBase<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.Subject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Threading.Tasks.TaskObservableExtensions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.CompilerServices.TaskObservableMethodBuilder<>))]
