// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT License.
// See the LICENSE file in the project root for more information.

using Corvus.Json;

using NodaTime;

using RxGauntlet.Build;
using RxGauntlet.LogModel;

namespace CheckIssue1745;

/// <summary>
/// Executes the bloat check for a single scenario.
/// </summary>
/// <remarks>
/// <para>
/// This creates a modified copy of the <c>Bloat.ConsoleWinRtTemplate</c> project, modifying the project file as
/// required by the scenario, builds it, and then checks to see whether the WPF and Windows Forms components were
/// copied into the build output.
/// </para>
/// <para>
/// Note that this does not have an opinion on whether the presence of those components is an error. Some of the
/// scenarios generated by <see cref="CheckDeploymentBloatCommand"/> include settings in which we expect and
/// want the desktop framework to be included. Programs or humans inspecting the output of this test will need
/// to determine whether or not the reported results indicate a problem.
/// </para>
/// </remarks>
internal class RunDeploymentBloatCheck
{
    public static async Task<Issue1745TestRun> RunAsync(string testRunId, OffsetDateTime testRunDateTime, Scenario scenario, string? packageSource)
    {
        Console.WriteLine(scenario);
        var tfm = scenario.WindowsVersion is string windowsVersion
            ? $"{scenario.BaseNetTfm}-{windowsVersion}"
            : scenario.BaseNetTfm;

        DirectoryInfo templateProjectFolder = new(
            Path.Combine(AppContext.BaseDirectory, "../../../../Bloat.ConsoleWinRtTemplate/"));


#pragma warning disable IDE0063 // Use simple 'using' statement
        using (var projectClone = ModifiedProjectClone.Create(
            templateProjectFolder.FullName,
            "CheckIssue1745",
            (projectFileRewriter) => RewriteProjectXmlDocument(
                projectFileRewriter,
                tfm,
                [scenario.RxMainPackage],
                scenario.UseWpf,
                scenario.UseWindowsForms,
                scenario.EmitDisableTransitiveFrameworkReferences),
                packageSource is not null ? [("loc", packageSource)] : null))
        {
            var buildResult = await projectClone.RunDotnetPublish("Bloat.ConsoleWinRtTemplate.csproj");

            (var includesWpf, var includesWindowsForms) = buildResult.CheckForUiComponentsInOutput();

            Console.WriteLine($"WPF: {includesWpf}");
            Console.WriteLine($"Windows Forms: {includesWindowsForms}");
            Console.WriteLine();

            var rxVersionPackage = NuGetPackage.Create(
                id: scenario.RxMainPackage.PackageId,
                version: scenario.RxMainPackage.Version,
                packageSource: packageSource.AsNullableJsonString());

            // Note: currently this test run has no specialized config so the schema generation
            // doesn't create a type to represent issue1745TestRunConfig. That's why we use
            // the common TestRunConfigWithUiFrameworkSettings here.
            var config = TestRunConfigWithUiFrameworkSettings.Create(
                baseNetTfm: scenario.BaseNetTfm,
                emitDisableTransitiveFrameworkReferences: scenario.EmitDisableTransitiveFrameworkReferences,
                // TODO: shouldn't we be capturing all packages, not just the first?
                // Also, really want to be sharing this code because all test types need to log this.
                rxVersion: rxVersionPackage,
                useWindowsForms: scenario.UseWindowsForms,
                windowsVersion: scenario.WindowsVersion,
                useWpf: scenario.UseWpf);
            if (scenario.WindowsVersion is string wv)
            {
                config = config.WithWindowsVersion(wv);
            }

            return Issue1745TestRun.Create(
                config: config,
                deployedWindowsForms: includesWindowsForms,
                deployedWpf: includesWpf,
                testRunDateTime: testRunDateTime,
                testRunId: testRunId);
        }
#pragma warning restore IDE0063 // Use simple 'using' statement
    }

    private static void RewriteProjectXmlDocument(
        ProjectFileRewriter project,
        string tfm,
        PackageIdAndVersion[] replaceSystemReactiveWith,
        bool? useWpf,
        bool? useWindowsForms,
        bool emitDisableTransitiveFrameworkReferences)
    {
        project.SetTargetFramework(tfm);
        project.ReplacePackageReference("System.Reactive", replaceSystemReactiveWith);
        project.AddUseUiFrameworksIfRequired(useWpf, useWindowsForms);

        if (emitDisableTransitiveFrameworkReferences)
        {
            project.AddPropertyGroup([new("DisableTransitiveFrameworkReferences", "True")]);
        }
    }
}
