// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPatternSourceBase<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPattern<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.EventPattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.TimeInterval<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Timestamped))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Timestamped<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.HistoricalScheduler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.HistoricalSchedulerBase))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeSchedulerBase<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeSchedulerExtensions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Concurrency.VirtualTimeScheduler<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Pattern<,,,,,,,,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Joins.Plan<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.LocalQueryMethodImplementationTypeAttribute))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Linq.Observable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.AsyncSubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.BehaviorSubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.ReplaySubject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.Subject))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.SubjectBase<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Subjects.Subject<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Reactive.Threading.Tasks.TaskObservableExtensions))]
